# -*- coding: utf-8 -*-
"""Basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zimil5ZOR8_2hp84KUPNetiAF4LwkBc6
"""

print("Hello world")
print("Welcome To my world")

#singal line and multiline comments
'''
Welcome to my house

'''
print("Hello")

#Variable declaration
a = 10
type(a)

print(a)

tenth=10
b=40
c="pradip"

type(c)

1a =10 #invalid syntax

a1 =10

first_name ="pradip"
print(first_name)

#integers
a =10
type(a)

a = 10
b = 20
print(a + b)

#floting
a =190.5
print(type(a))

#typecasting
int(a)

float(b)

##Boolean
a1 = True
b1 = False

type(a1)

a1 and b1

a1 or b1

a1 | b1

#strings
name1 ="Pradip"
print(name1)
print(type(name1))

name1 + "bhattacharjya"

name1 + str(1)

#complex numbers
j=1.0-2.3j
j

print(j.real,j.imag)

#dynamic typing
a = 10
a ='Pradip'

print(a)

#strong typing
a = "KRish"

a + str(1)

#string Formatting
a= 100
print("The values is -",a)

first_name= "Pradip"
last_name= "bhattacharjya"
print("The first name is {} and last name is {}".format(first_name,last_name))

# input type
input("Enter the name")

a=input("Enter the number A")
b=input("Enter the number B")

print(int(a) + int(b))