# -*- coding: utf-8 -*-
"""Loops And Control Statements.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1grelAGQ87TKQtX8oQUANwzS-rWZITWrL

Control Flows
"""

#if statement
val =input("Enter the number")
value_float=float(val)
if(value_float >100):
  print("the number is greater then 100")

val =input("Enter the number")
value_float=float(val)
if(value_float % 2 == 0):
  print("the number is even ")

#if-else statement
val =input("Enter the number")
value_float=float(val)
if(value_float % 2 == 0):
  print("the number is even ")
else:
  print("The number is odd")

##Age form
##Nested if else condition
age =float(input("Enter the age"))

if(age<18):
  print("Minor Age")
elif(age>=18 and age<=35):
  print("Mid age")
elif(age>45 and age<=50):
  print("Senior Mid Age")
else:
  print("Senior Citizen")

#nested iflese
age =float(input("Enter the age"))

if(age<18):
  print("Minor Age")
  if(age<15):
    print("you are in School")
  else:
    print("You are in College")
elif(age>=18 and age<=35):
  print("Mid age")
elif(age>45 and age<=50):
  print("Senior Mid Age")
else:
  print("Senior Citizen")

##loops statement
## for loop, while loop

lst=[1,2,3,4,5,6,7]
for i in lst:
  print(i*2)

##find the sum of all the elements in the list
lst=[1,2,3,4,5,6,7]
sum1 = 0
for i in lst:
  sum1=sum1 + i
print(sum1)

##find the sum of even and odd number
lst=[1,2,3,4,5,6,7]
even_sum =0
odd_sum =0

for i in lst:
  if(i%2==0):
    even_sum=even_sum+i
  else:
    odd_sum=odd_sum+i
print("Even sum is {}".format(even_sum))
print("Even sum is {}".format(odd_sum))

##While condition

i=0
while(i<=10):
  print(i)
  i=i+1

i =0
even_sum=0
odd_sum=0
while(i<=10):

  if(i%2==0):
    enven_sum=even_sum + i
  else:
    odd_sum=odd_sum + i

  i=i+1
print(even_sum,odd_sum)

#break
x=1
while(x<7):


  if x==4:
    break
  print(x)
  x=x+1

##continue
x =0

while x<7:
  x=x+1
  if x==4:
    continue
  print(x)